name: flutter_time_guard
description: Flutter Time Guard is used to detect system time changes and validate device time using NTP, ensuring reliable and secure time-sensitive operations.
version: 0.0.6
homepage: https://github.com/M-Yahia2011/flutter_time_guard.git
repository: https://github.com/M-Yahia2011/flutter_time_guard
issue_tracker: https://github.com/M-Yahia2011/flutter_time_guard/issues
documentation: https://github.com/M-Yahia2011/flutter_time_guard#readme



environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  ntp: ^2.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.myahia.flutter_time_guard
        pluginClass: FlutterTimeGuardPlugin
      ios:
        pluginClass: FlutterTimeGuardPlugin

topics:
  - time
  - ntp
  - datetime
  - security

license: MIT
